#!/usr/bin/env python3
"""
Single source of truth for "which examples/tests/sandbox entries build with which board/flags".

Reads every examples/*/iotsa-build.json, tests/*/iotsa-build.json, and
sandbox/*/iotsa-build.json and turns them into:
  - the toplevel platformio.ini env list (--format=platformio-ini)
  - a GitHub Actions matrix, per CI backend (--format=github-matrix --backend=...)
  - a standalone platformio.ini for a single entry (--format=standalone-ini --dir=...)

See docs/module-interface-status.md and the #156/#222 discussions for background.
"""
import argparse
import io
import json
import os
import sys

REPO_ROOT = os.path.normpath(os.path.join(os.path.dirname(__file__), "..", ".."))

# Maps our short board name (also the platformio.ini scaffolding section name)
# to the actual PlatformIO board ID and, where supported, the arduino-cli FQBN.
BOARD_INFO = {
    "nodemcuv2":        {"pio_board": "nodemcuv2",           "fqbn": "esp8266:esp8266:nodemcuv2"},
    "esp32thing":       {"pio_board": "esp32thing",           "fqbn": "esp32:esp32:esp32thing"},
    "esp32dev":         {"pio_board": "esp32dev",              "fqbn": None},
    "lolin32":          {"pio_board": "lolin32",               "fqbn": None},
    "pico32":           {"pio_board": "pico32",                "fqbn": None},
    "esp32c3devkit":    {"pio_board": "esp32-c3-devkitm-1",    "fqbn": None},
    "esp32c3lcd":       {"pio_board": "esp32-c3-devkitm-1",    "fqbn": None},
    "esp32c3supermini": {"pio_board": "esp32-c3-devkitm-1",    "fqbn": None},
    "crowpanel128":     {"pio_board": "esp32-c3-devkitm-1",    "fqbn": None},
    "esp32s3supermini": {"pio_board": "esp32-s3-devkitc-1",    "fqbn": "esp32:esp32:esp32s3"},
}


def merge_patch(default, override):
    """RFC 7396 JSON Merge Patch: override replaces default per top-level key;
    a null value in override deletes that key."""
    result = dict(default or {})
    for k, v in (override or {}).items():
        if v is None:
            result.pop(k, None)
        else:
            result[k] = v
    return result


def load_entries():
    """Returns a list of dicts, one per (directory, variant), fully merged."""
    entries = []
    for kind, base in (("example", "examples"), ("test", "tests"), ("sandbox", "sandbox")):
        base_dir = os.path.join(REPO_ROOT, base)
        if not os.path.isdir(base_dir):
            continue
        for name in sorted(os.listdir(base_dir)):
            build_json = os.path.join(base_dir, name, "iotsa-build.json")
            if not os.path.isfile(build_json):
                continue
            with open(build_json) as f:
                spec = json.load(f)
            source = spec.get("source", f"{base}/{name}")
            defaults = spec.get("defaults", {})
            for variant in spec["variants"]:
                merged = merge_patch(defaults, variant)
                merged["kind"] = kind
                merged["name"] = name
                merged["source"] = source
                # tests/ exists specifically to hold minimal-complete-coverage variants
                # (see #216) -- every test entry counts by default. sandbox/ (#222)
                # defaults the same way: it's under active development, so it wants
                # fast feedback on every develop push, not just full-tier runs. An
                # example only counts if it says so explicitly (it covers a
                # module/combination no test/sandbox entry does either).
                merged.setdefault("minimal", kind in ("test", "sandbox"))
                merged.setdefault("ci", {"platformio": True, "arduino": False})
                merged.setdefault("build_flags", [])
                merged.setdefault("lib_deps", [])
                entries.append(merged)
    return entries


def env_name(e):
    parts = [e["board"], e["kind"], e["name"]]
    if e.get("label"):
        parts.append(e["label"])
    return "-".join(parts)


def emit_platformio_ini(entries, out):
    out.write("; Generated by extras/python/gen_build_matrix.py from examples/*/iotsa-build.json,\n")
    out.write("; tests/*/iotsa-build.json, and sandbox/*/iotsa-build.json -- do not hand-edit,\n")
    out.write("; regenerate instead:\n")
    out.write(";   python3 extras/python/gen_build_matrix.py --format=platformio-ini -o generated_envs.ini\n\n")
    skips = []
    for e in entries:
        if not e["ci"].get("platformio", True):
            continue
        board = e["board"]
        info = BOARD_INFO.get(board)
        if info is None:
            print(f"warning: unknown board {board!r}, skipping env for {env_name(e)}",
                  file=sys.stderr)
            continue
        out.write(f"[env:{env_name(e)}]\n")
        out.write(f"extends = {board}\n")
        out.write(f"build_src_filter = +<*> +<../{e['source']}>\n")
        if e["build_flags"]:
            out.write(f"build_flags = ${{{board}.build_flags}} {' '.join(e['build_flags'])}\n")
        if e.get("partitions"):
            out.write(f"board_build.partitions = {e['partitions']}\n")
        if e["lib_deps"]:
            out.write(f"lib_deps = \n")
            out.write(f"    ${{{board}.lib_deps}}\n")
            for dep in e["lib_deps"]:
                out.write(f"    {dep}\n")
        out.write("\n")
        skip_reason = (e.get("skip") or {}).get("platformio")
        if skip_reason:
            skips.append((env_name(e), "platformio", skip_reason))
    for name, backend, reason in skips:
        print(f"note: {name} generated for local dev, but CI skips it "
              f"({backend}): {reason}", file=sys.stderr)


def emit_github_matrix(entries, backend, tier, out):
    matrix = []
    skips = []
    for e in entries:
        if not e["ci"].get(backend, False):
            continue
        if tier == "minimal" and not e["minimal"]:
            continue
        skip_reason = (e.get("skip") or {}).get(backend)
        if skip_reason:
            skips.append((env_name(e), skip_reason))
            continue
        board = e["board"]
        info = BOARD_INFO.get(board)
        if info is None:
            print(f"warning: unknown board {board!r}, skipping {env_name(e)}",
                  file=sys.stderr)
            continue
        item = {
            "name": env_name(e),
            "kind": e["kind"],
            "example": e["name"],
            "source": e["source"],
            "board": board,
            "build_flags": " ".join(e["build_flags"]),
            # newline-joined, not a JSON list: GitHub Actions matrix values are consumed
            # as plain strings in the job's env block, so lists are awkward there. A
            # newline-joined string plugs directly into a multi-line platformio
            # --project-option="lib_deps=..." value, the same list syntax platformio.ini
            # itself uses.
            "extra_lib_deps": "\n".join(e["lib_deps"]),
            "partitions": e.get("partitions") or "",
        }
        if backend == "platformio":
            item["pio_board"] = info["pio_board"]
        elif backend == "arduino":
            if not info["fqbn"]:
                print(f"warning: board {board!r} has no arduino-cli FQBN, "
                      f"skipping {env_name(e)}", file=sys.stderr)
                continue
            item["fqbn"] = info["fqbn"]
            partitions = e.get("partitions")
            if partitions == "min_spiffs.csv":
                item["partition_scheme"] = "min_spiffs"
        matrix.append(item)
    for name, reason in skips:
        print(f"note: skipping {name} for {backend}: {reason}", file=sys.stderr)
    # Compact, single-line: this is meant to be captured directly into a
    # $GITHUB_OUTPUT value, where a multi-line value needs extra heredoc ceremony.
    json.dump({"include": matrix}, out, separators=(",", ":"))
    out.write("\n")


def iotsa_lib_deps(target_dir):
    """Where should this standalone example's iotsa dependency come from?

    <target_dir>/iotsa-config.json can set a toplevel "iotsa" field to an
    explicit lib_deps-style value (a git URL#ref, to pin against a specific
    published branch/tag). Absent that, we default to a symlink at the local
    iotsa checkout this example lives in -- anyone who has this file at all
    has necessarily cloned the enclosing repo, so the relative path is always
    valid, and it means local framework edits are picked up without needing
    to push first.
    """
    config_path = os.path.join(target_dir, "iotsa-config.json")
    if os.path.isfile(config_path):
        with open(config_path) as f:
            config = json.load(f)
        if config.get("iotsa"):
            return config["iotsa"]
    return f"symlink://{os.path.relpath(REPO_ROOT, target_dir)}"


def emit_standalone_ini(entries, target_dir, out):
    rel = os.path.relpath(target_dir, REPO_ROOT)
    # Kind-agnostic (source, not a hardcoded "examples/" prefix) so this also works
    # for a self-contained sandbox/ entry (#222), not just examples/.
    own = [e for e in entries if e["source"] == rel and e["ci"].get("platformio", True)]
    if not own:
        print(f"note: {rel} has no platformio-enabled variants, no standalone "
              f"platformio.ini to generate", file=sys.stderr)
        return
    out.write("; PlatformIO Project Configuration File\n")
    out.write("; Generated by extras/python/gen_build_matrix.py -- do not hand-edit,\n")
    out.write("; regenerate instead:\n")
    out.write(";   python3 extras/python/gen_build_matrix.py --format=standalone-ini \\\n")
    out.write(f";     --dir={rel} -o {rel}/platformio.ini\n")
    out.write("; To pin this example against a specific published iotsa branch/tag\n")
    out.write("; instead of the local checkout, add an iotsa-config.json here:\n")
    out.write(';   {"iotsa": "https://github.com/cwi-dis/iotsa.git#develop"}\n')
    out.write(";\n")
    # A board can appear more than once (e.g. a plain variant plus a differently
    # labeled one, as with sandbox/BLEClient's merged matrix, #222) -- suffix the
    # env name with the label whenever one is present, so two variants sharing a
    # board don't collide into the same [env:xxx] section.
    env_names = [e["board"] if not e.get("label") else f"{e['board']}-{e['label']}"
                 for e in own]
    out.write("[platformio]\n")
    out.write("src_dir = .\n")
    out.write(f"default_envs = {env_names[0]}\n\n")
    out.write("[common]\n")
    out.write("framework = arduino\n")
    out.write("lib_ldf_mode = deep+\n")
    out.write("lib_compat_mode = strict\n")
    out.write(f"lib_deps = {iotsa_lib_deps(target_dir)}\n")
    out.write("monitor_speed = 115200\n\n")
    for e, env in zip(own, env_names):
        board = e["board"]
        info = BOARD_INFO[board]
        out.write(f"[env:{env}]\n")
        out.write("extends = common\n")
        out.write(f"platform = {'espressif8266' if board == 'nodemcuv2' else 'espressif32'}\n")
        out.write(f"board = {info['pio_board']}\n")
        if e["build_flags"]:
            out.write(f"build_flags = {' '.join(e['build_flags'])}\n")
        if e.get("partitions"):
            out.write(f"board_build.partitions = {e['partitions']}\n")
        if e["lib_deps"]:
            out.write("lib_deps = \n")
            out.write("    ${common.lib_deps}\n")
            for dep in e["lib_deps"]:
                out.write(f"    {dep}\n")
        out.write("\n")


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--format", required=True,
                     choices=["platformio-ini", "github-matrix", "standalone-ini"])
    ap.add_argument("--backend", choices=["platformio", "arduino"],
                     help="required for --format=github-matrix")
    ap.add_argument("--tier", choices=["full", "minimal"], default="full",
                     help="--format=github-matrix only: 'minimal' builds just the "
                          "tests/ tree plus examples explicitly marked minimal:true "
                          "(see #216); default 'full' builds everything")
    ap.add_argument("--dir", help="examples/<Name> dir, required for --format=standalone-ini")
    ap.add_argument("-o", "--output", help="write to file instead of stdout")
    args = ap.parse_args()

    entries = load_entries()

    if args.format == "standalone-ini":
        # Buffered: a directory with no platformio-enabled variants emits nothing,
        # and any stale output file (e.g. from before a variant dropped platformio
        # coverage) must be removed rather than left behind as an empty/stale file.
        if not args.dir:
            ap.error("--format=standalone-ini requires --dir")
        buf = io.StringIO()
        emit_standalone_ini(entries, os.path.join(REPO_ROOT, args.dir), buf)
        content = buf.getvalue()
        if not content:
            if args.output and os.path.exists(args.output):
                os.remove(args.output)
            return
        if args.output:
            with open(args.output, "w") as out:
                out.write(content)
        else:
            sys.stdout.write(content)
        return

    out = open(args.output, "w") if args.output else sys.stdout
    try:
        if args.format == "platformio-ini":
            emit_platformio_ini(entries, out)
        elif args.format == "github-matrix":
            if not args.backend:
                ap.error("--format=github-matrix requires --backend")
            emit_github_matrix(entries, args.backend, args.tier, out)
    finally:
        if args.output:
            out.close()


if __name__ == "__main__":
    main()
