language: python
python:
- '3.6'
env:
- IOTSA_EXAMPLE=Hello PLATFORMIO_CI_SRC=examples/Hello
- IOTSA_EXAMPLE=HelloApi PLATFORMIO_CI_SRC=examples/HelloApi
- IOTSA_EXAMPLE=HelloCpp PLATFORMIO_CI_SRC=examples/HelloCpp
- IOTSA_EXAMPLE=HelloPasswd PLATFORMIO_CI_SRC=examples/HelloPasswd
- IOTSA_EXAMPLE=HelloRights PLATFORMIO_CI_SRC=examples/HelloRights
- IOTSA_EXAMPLE=HelloToken PLATFORMIO_CI_SRC=examples/HelloToken
- IOTSA_EXAMPLE=HelloUser PLATFORMIO_CI_SRC=examples/HelloUser
- IOTSA_EXAMPLE=Led PLATFORMIO_CI_SRC=examples/Led
- IOTSA_EXAMPLE=Light PLATFORMIO_CI_SRC=examples/Light
- IOTSA_EXAMPLE=Log PLATFORMIO_CI_SRC=examples/Log
- IOTSA_EXAMPLE=Skeleton PLATFORMIO_CI_SRC=examples/Skeleton
- IOTSA_EXAMPLE=Button PLATFORMIO_CI_SRC=examples/Button
- IOTSA_EXAMPLE=Ringer PLATFORMIO_CI_SRC=examples/Ringer
# Temporarily removed, see https://github.com/platformio/platform-espressif32/issues/301
# - IOTSA_EXAMPLE=BLELed PLATFORMIO_CI_SRC=examples/BLELed PLATFORMIO_CI_EXTRA_ARGS='--project-option="board_build.partitions=no_ota.csv"'
# Build a service coap-only (no web, no http[s])
- IOTSA_EXAMPLE=Led PLATFORMIO_CI_SRC=examples/Led PLATFORMIO_BUILD_FLAGS="-DIOTSA_WITH_COAP -DIOTSA_WITHOUT_WEB -DIOTSA_WITHOUT_REST -DIOTSA_WITHOUT_HTTP -DIOTSA_WITHOUT_HTTPS -DIOTSA_WITH_PLACEHOLDERS"
# Build a service with both coap and rest/web
- IOTSA_EXAMPLE=Led PLATFORMIO_CI_SRC=examples/Led PLATFORMIO_BUILD_FLAGS="-DIOTSA_WITH_COAP -DIOTSA_WITH_REST"
# Build a service with https in stead of http
# - IOTSA_EXAMPLE=Led PLATFORMIO_CI_SRC=examples/Led PLATFORMIO_BUILD_FLAGS="-DIOTSA_WITHOUT_HTTP -DIOTSA_WITH_HTTPS"
# Build a coap-only service that uses requests
- IOTSA_EXAMPLE=Button PLATFORMIO_CI_SRC=examples/Button PLATFORMIO_BUILD_FLAGS="-DIOTSA_WITH_COAP -DIOTSA_WITHOUT_WEB -DIOTSA_WITHOUT_REST -DIOTSA_WITHOUT_HTTP -DIOTSA_WITHOUT_HTTPS -DIOTSA_WITH_PLACEHOLDERS"
install:
- pip install -U platformio
- python --version
- pip --version
- platformio --version
- platformio lib -g install "Adafruit NeoPixel@~1.3.5"
- platformio lib -g install "Time@>=1.6"
- platformio lib -g install "Timezone@~1.2.4"
- platformio lib -g install "ArduinoJson@~6.14.1"
- platformio lib -g install "ArduinoJWT@~1.0.1"
- platformio lib -g install "CoAP simple library@~1.3.19"
- platformio lib -g install "esp32_https_server_compat@~1.0.0"
script:
- platformio ci --lib="." --project-option="lib_ldf_mode=deep+" --board=nodemcuv2  $PLATFORMIO_CI_EXTRA_ARGS
- platformio ci --lib="." --project-option="lib_ldf_mode=deep+" --board=esp32thing  $PLATFORMIO_CI_EXTRA_ARGS
