language: python
python:
- '2.7'
env:
- PLATFORMIO_CI_SRC=examples/Hello
- PLATFORMIO_CI_SRC=examples/HelloApi
- PLATFORMIO_CI_SRC=examples/HelloCpp
- PLATFORMIO_CI_SRC=examples/HelloPasswd
- PLATFORMIO_CI_SRC=examples/HelloRights
- PLATFORMIO_CI_SRC=examples/HelloToken
- PLATFORMIO_CI_SRC=examples/HelloUser
- PLATFORMIO_CI_SRC=examples/Led
- PLATFORMIO_CI_SRC=examples/Light
- PLATFORMIO_CI_SRC=examples/Log
- PLATFORMIO_CI_SRC=examples/Skeleton
- PLATFORMIO_CI_SRC=examples/Button
- PLATFORMIO_CI_SRC=examples/Ringer
install:
- pip install -U platformio
- platformio lib -g install "Adafruit NeoPixel@~1.1.6"
- platformio lib -g install "Time@>=1.5"
- platformio lib -g install "Timezone@~1.1.1"
- platformio lib -g install "ArduinoJson@~5.13.0"
- platformio lib -g install "ArduinoJWT@~1.0.1"
script:
- platformio ci --lib="." --board=nodemcuv2
- platformio lib -g install "ESP32WebServer" && platformio ci --lib="." --board=esp32thing
