# Created this action based on information found in:
# - <https://github.com/marketplace/actions/test-compile-for-arduino>
# - <https://docs.github.com/en/free-pro-team@latest/actions/quickstart>
name: build-arduino
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arduino-board-fqbn:
        - esp32:esp32:esp32thing
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Checkout custom library
      uses: actions/checkout@v2
      with:
        repository: yutter/ArduinoJWT
        path: CustomLibrary_ArduinoJWT 
    - name: Arduino build
      uses: ArminJo/arduino-test-compile@v3
      with:
        platform-url: https://arduino.esp8266.com/stable/package_esp8266com_index.json,https://dl.espressif.com/dl/package_esp32_index.json
        arduino-board-fqbn: ${{ matrix. arduino-board-fqbn }}
        required-libraries: Adafruit NeoPixel,Time,Timezone,ArduinoJson,CoAP simple library,ESP32_HTTPS_Server,esp32_https_server_compat
        debug-compile: true
        debug-install: true